force-app/main/default/objects/compliancequest__SQX_Part__c/compliancequest__SQX_Part__c.object-meta.xml
<CustomObject>
    <description>Object to list all Parts</description>
    <label>Part</label>
    <nameField>
        <label>Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/compliancequest__SQX_Part__c/fields/compliancequest__Part_Family__c.field-meta.xml
<CustomField>
    <fullName>compliancequest__Part_Family__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Describes the Family/Category to which a Part belongs to.</description>
    <label>Part Family</label>
    <referenceTo>compliancequest__SQX_Part_Family__c</referenceTo>
    <relationshipLabel>Parts</relationshipLabel>
    <relationshipName>SQX_Parts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/compliancequest__SQX_Part__c/fields/compliancequest__Part_Number__c.field-meta.xml
<CustomField>
    <fullName>compliancequest__Part_Number__c</fullName>
    <description>Unique text to identify a Part.</description>
    <externalId>true</externalId>
    <label>Part Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/compliancequest__SQX_Part__c/fields/compliancequest__Part_Risk_Level__c.field-meta.xml
<CustomField>
    <fullName>compliancequest__Part_Risk_Level__c</fullName>
    <description>1-5 : 1 being HIGHEST Risk and 5 being LOWEST Risk</description>
    <inlineHelpText>1-5 : 1 being HIGHEST Risk and 5 being LOWEST Risk</inlineHelpText>
    <label>Part Risk Level</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PartTriggerControllerTest.cls
/*
  ** Author Name : ----
  ** Description : Write a Test class for PartTriggerController this controller.
  ** Class name : PartTriggerControllerTest it is use in Trigger is PartTrigger and Controller class is PartTriggerController.
*/

@isTest
public class PartTriggerControllerTest 
{
    @isTest
    public static void TestData()
    {
        compliancequest__SQX_Part_Family__c prfamily = new compliancequest__SQX_Part_Family__c();
        prfamily.Name = 'test data';
        insert prfamily;
        
        compliancequest__SQX_Part__c pr = new compliancequest__SQX_Part__c();
        pr.Name = 'test data';
        pr.compliancequest__Part_Number__c = '123';
        pr.compliancequest__Part_Risk_Level__c = 1;
        pr.compliancequest__Part_Family__c = prfamily.id;
        insert pr;
        
        Task tsk = new Task();
        tsk.WhatId = pr.Id;
        tsk.Subject = 'Review Part -' + pr.compliancequest__Part_Number__c;
        tsk.OwnerId = pr.CreatedById;
        tsk.Status = 'Not Started';
        insert tsk;
    }

}